import fs from "fs";
import path from "path";
// Inline the real source of key project files so the Code app can show them at runtime.
const ROOT = path.resolve(import.meta.dirname, "..");
const files = [
  ["store.ts", "lib/store.ts"],
  ["terminal", "components/apps/TerminalApp.tsx"],
  ["window", "components/Window.tsx"],
  ["dock", "components/Dock.tsx"],
  ["system", "lib/system.ts"],
];
const out = [];
for (const [label, rel] of files) {
  const src = fs.readFileSync(path.resolve(ROOT, rel), "utf8");
  out.push(`  ${JSON.stringify(label)}: ${JSON.stringify(src)}`);
}
const module = `// Auto-generated by scripts/snapshot-source.mjs — do not edit.\nexport const SAMPLES: Record<string,string> = {\n${out.join(",\n")},\n};\n`;
fs.writeFileSync(path.resolve(ROOT, "lib", "source-snapshots.ts"), module);
console.log("wrote lib/source-snapshots.ts");
